version: '3.3'

services:
  app:
    depends_on:
      - estcmd 
    build: ./lighttpd
    volumes:
      - ./index:/index
      - ./lighttpd/configuration:/configuration
      - ./lighttpd/startscript:/startscript
    ports: 
     - 80:80
    restart: always
    networks:
      - default
  estcmd:
    build: ./estcmd
    volumes:
      - ./index:/index
      - ./source:/source
      - ./estcmd/startscript:/startscript
      - ./estcmd/cron_configuration:/cron_configuration
    networks:
      - default
  